stages:
  fig-from-excel:
    cmd: calkit office excel-chart-to-png data.xlsx --sheet=1 --chart-index=0
      figures/chart.png
    deps:
      - data.xlsx
    outs:
      - figures/chart.png
  word-to-pdf:
    cmd: calkit office word-to-pdf paper.docx paper.pdf
    deps:
      - paper.docx
      - figures/chart.png
    outs:
      - paper.pdf
