stages:
  extract-chart:
    cmd: calkit office excel-chart-to-image "data.xlsx" --sheet=1 --chart-index=0
      "figures/chart.png"
    deps:
      - data.xlsx
    outs:
      - figures/chart.png
  export-pdf:
    cmd: calkit office word-to-pdf "paper.docx" --output "paper.pdf"
    deps:
      - paper.docx
    outs:
      - paper.pdf
